#Titus Learning Continuous Integration
#Code standards compliance through PHPSniff
#Automated testining with PHPUnit and Behat
#Validate at https://bitbucket-pipelines.atlassian.io/validator
pipelines:
  pull-requests:
      '**':
         - step:
             name: PHPSniffer
             #image: atlassian/default-image:2
             image: composer:1.9
             script:
             # Customise ruleset.xml or remove references for full moodle code compliance
             - cp ruleset.xml moodle
             - composer global require "squizlabs/php_codesniffer=2.*"
             - composer global install
             - composer require --dev "blackboard-open-source/moodle-coding-standard"
             - export PATH="$HOME:/tmp/vendor/squizlabs/php_codesniffer/scripts/phpcs:$PATH"
             - /tmp/vendor/squizlabs/php_codesniffer/scripts/phpcs  --config-set  installed_paths /opt/atlassian/pipelines/agent/build/vendor/blackboard-open-source/moodle-coding-standard
             #- /tmp/vendor/squizlabs/php_codesniffer/scripts/phpcs --extensions=php --standard=moodle  moodle/local/yourplugin
         - step:
            name: PHPUnit and Behat
            image: atlassian/default-image:2
            script:
             # Get Moodle (Comment out this block if you want to use MWP)
             # Branches available v3.8.2 v3.7.5 v3.6.9 3.5.11
             - MOODLE_BRANCH="v3.8.2"
             - wget github.com/moodle/moodle/archive/$MOODLE_BRANCH".zip"
             - unzip -qq $MOODLE_BRANCH".zip"

             # Get MWP (Uncomment from line - wget if you want to use MWP)
             # Until we get some kind of tagging set up for the repo, we are just going to have to use master with no tags.
             # This is bad as it means we always get the latest version which might not be appropriate.
             # Note: The BB_USER and BB_APPPWD variables below are repository variables stored in bitbucket:
             # https://bitbucket.org/titus-learning/titus-moodle/admin/addon/admin/pipelines/repository-variables
             # - wget https://$BB_USER:$BB_APPPWD@bitbucket.org/titus-learning/moodle_workplace/get/master.zip
             # - unzip -qq "master.zip"

             - cp composer.phar moodle
             - cp -R titus-learning-moodle_workplace-*/* moodle
             - cp scripts/ci/packagetests.php moodle/packagetests.php
             - cp package.json moodle/project_package.json
             - chmod 755 moodle/packagetests.php
             - git clone https://github.com/moodlehq/moodle-docker
             - export MOODLE_DOCKER_WWWROOT=/opt/atlassian/pipelines/agent/build/moodle
             - export MOODLE_DOCKER_DB=pgsql #or mysql
             - cd moodle-docker
             - cp config.docker-template.php $MOODLE_DOCKER_WWWROOT/config.php
             - bin/moodle-docker-compose up -d
             - bin/moodle-docker-wait-for-db
             - bin/moodle-docker-compose exec -T webserver php admin/tool/phpunit/cli/init.php
             # Run ALL the php unit tests for all plugins specified in package.json
             - bin/moodle-docker-compose exec -T webserver php packagetests.php

             # Behat could be run in its own step, but that would add to the time taken
             #- bin/moodle-docker-compose exec -T webserver php admin/tool/behat/cli/init.php
             #- bin/moodle-docker-compose exec -T -u www-data webserver php admin/tool/behat/cli/run.php --tags=@yourtags
            services:
              - docker
definitions:
  services:
    docker:
      memory: 3072
