#Titus Learning Continuous Integration
#Code standards compliance through PHPSniff
#Automated testining with PHPUnit and Behat
#Validate at https://bitbucket-pipelines.atlassian.io/validator
pipelines:
  pull-requests:
      '**':
         - step:
             name: PHPSniffer
             #image: atlassian/default-image:2
             image: composer:1.9
             script:
             # Customise ruleset.xml or remove references for full moodle code compliance
             # - cp ruleset.xml moodle
             # - composer global require "squizlabs/php_codesniffer=2.*"
             # - composer global install
             # - composer require --dev "blackboard-open-source/moodle-coding-standard"
             # - export PATH="$HOME:/tmp/vendor/squizlabs/php_codesniffer/scripts/phpcs:$PATH"
             # - /tmp/vendor/squizlabs/php_codesniffer/scripts/phpcs  --config-set  installed_paths /opt/atlassian/pipelines/agent/build/vendor/blackboard-open-source/moodle-coding-standard
             # - /tmp/vendor/squizlabs/php_codesniffer/scripts/phpcs --extensions=php --standard=moodle  moodle/theme/cass
         - step:
            name: PHPUnit and Behat
            image: atlassian/default-image:2
            script:
             - apt-get update && apt-get install -y
             - apt-get install jq -y
             - chmod 755 scripts/ci/getmoodle.sh
             - scripts/ci/getmoodle.sh $BB_USER $BB_APPPWD
             # This is seriously bad but without changing to 777, the moodle docker web server can't
             # run composer and populate the vendor folder.
             - chmod 777 -R moodle
             - ls -all
             - cp composer.phar moodle
             - cp scripts/ci/packagetests.php moodle/packagetests.php
             - cp package.json moodle/project_package.json
             - chmod 755 moodle/packagetests.php
             - git clone https://github.com/moodlehq/moodle-docker
             - export MOODLE_DOCKER_WWWROOT=/opt/atlassian/pipelines/agent/build/moodle
             - export MOODLE_DOCKER_DB=pgsql #or mysql
             - cd moodle-docker
             - cp config.docker-template.php $MOODLE_DOCKER_WWWROOT/config.php
             - bin/moodle-docker-compose up -d
             - bin/moodle-docker-wait-for-db
             - bin/moodle-docker-compose exec -T webserver php admin/tool/phpunit/cli/init.php
             #- bin/moodle-docker-compose exec -T webserver vendor/bin/phpunit  theme/cass/tests/. --test-suffix=test.php
             # Behat could be run in its own step, but that would add to the time taken
             #- bin/moodle-docker-compose exec -T webserver php admin/tool/behat/cli/init.php
             #- bin/moodle-docker-compose exec -T -u www-data webserver php admin/tool/behat/cli/run.php --tags=@yourtags
            services:
              - docker
definitions:
  services:
    docker:
      memory: 3072
