#!/usr/bin/env bash
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. ./base.sh

create_template () {
    LINES=""
    LINES+="# ---------------------------------------------\n"
    LINES+="# This file is automatically generated.\n"
    LINES+="# Add new plugins to package.json.\n"
    LINES+="# Add custom ignores to build/.gitignore.\n"
    LINES+="# ---------------------------------------------\n\n"
    LINES+="/moodle/*\n"

    NUM=`get_number_of_plugins`

    for i in `seq 0 $(($NUM-1))`
    do
        PLUGIN=`get_moodle plugins[$i]`
        # echo $PLUGIN
        # exit 0
        IFS='/' read -r -a ARRAY <<< "$PLUGIN"
        COUNT="${#ARRAY[@]}"
        P="moodle"

        for ii in `seq 0 $(($COUNT-1))`
        do
            P="$P/${ARRAY[$ii]}"
            if [ $ii -lt $(($COUNT-1)) ]; then
                LINE="/${P}/*\n"
                # only add the new line if it isn't already present
                if [[ ! ("$LINES" =~ "$LINE") ]]; then
                    LINES="${LINES}${LINE}"
                fi
            fi
            LINE="!/${P}\n"

            # only add the new line if it isn't already present
            if [[ ! ("$LINES" =~ "$LINE") ]]; then
                LINES="${LINES}${LINE}"
            fi
        done
    done

    echo -e "${LINES}\n$(cat $SCRIPTS/template.gitignore)" > $ROOT/.gitignore
}

create_template
success "Written new .gitignore"
